services:
  - type: web
    name: microsite-tracker-backend
    env: node
    buildCommand: npm install && cd client && npm install && cd .. && npx prisma generate && npm run client:build
    startCommand: npm start
    deployCommand: echo "Build complete, starting server..."  # Override any dashboard deploy command setting
    healthCheckPath: /health
    plan: free  # Free tier
    envVars:
      - key: NODE_ENV
        value: production
      - key: IS_LOCAL
        value: false
      - key: USE_TEMP_STORAGE
        value: false
      # ⚠️ IMPORTANT: DATABASE_URL should be set in Render dashboard, not here!
      # ⚠️ PORT and CLIENT_URL should also be set in dashboard
      # ⚠️ Never commit production DATABASE_URL to Git!

  # Optional: PostgreSQL database (free tier)
  # Uncomment if you want Render to host your database
  # - type: pg
  #   name: microsite-tracker-db
  #   plan: free  # Free tier
  #   databaseName: microsite_tracker
  #   user: microsite_user

