name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Verify no .env files
        run: |
          if [ -f ".env" ]; then
            echo "❌ CRITICAL: .env file detected in repository!"
            echo "This should never be committed. Removing from tracking..."
            exit 1
          fi
          
          echo "✅ No sensitive files found"
      
      - name: Deployment Checklist
        run: |
          echo "🚀 Production Deployment Checklist:"
          echo "✅ Code pushed to main branch"
          echo "✅ All tests passed"
          echo "✅ No sensitive files in repository"
          echo ""
          echo "⚠️ Remember to:"
          echo "1. Set environment variables in hosting platform"
          echo "2. Verify DATABASE_URL points to production"
          echo "3. Set USE_TEMP_STORAGE=false"
          echo "4. Monitor deployment logs"

